import Head from 'next/head'
import Image from 'next/image'
import data from '../data.json';
import { useState } from 'react';
import pic from '../assets/images/desktop.png';
export default function Home() {
  const [planet, setPlanet] = useState(data[0]);
  const [category, setCategory] = useState(planet.overview);

    
  return (
    <div >
      <Head>
        <title>Planets Fact site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='p-5'>
        <div className='flex text-white justify-between items-center'>
          <img src={planet.images.internal} alt='logo' className='h-[20vh] w-[20vh]' />
            <div className='flex flex-col space-y-7'>
            <h1>
              {planet.name}
            </h1>
            <p>
              {category.content}
            </p>
            <p>
              {category.source}
            </p>
          <div className='flex flex-col w-[fit-content] space-y-5'>
            <h2
              onClick={() => {
                setCategory(planet.overview);
              }}
            className='border border-gray-400 px-10 py-4'>
              overview
            </h2>
            <h2 
              onClick={() => {
                setCategory(planet.structure);
              }}
            className='border border-gray-400 px-10 py-4'>
              internal structure
            </h2>
            <h2 
              onClick={() => {
                setCategory(planet.geology);
              }}
            className='border border-gray-400 px-10 py-4'>
              surface geology
            </h2>
          </div>
          </div>
      </div>
      </div>
      <div className='flex p-7 flex-row space-x-10 text-white w-[fit-content]'>
      <div className='border border-gray-400 px-20 py-4'>
          <h2 className='text-[10px]'>
              Revolution Time
            </h2>
            <p>
              {planet.revolution}
            </p>
          </div>
          <div className='border border-gray-400 px-20 py-4'>
          <h2 className='text-[10px]'>
              Revolution Time
            </h2>
            <p>
              {planet.revolution}
            </p>
          </div>
          <div className='border border-gray-400 px-20 py-4'>
          <h2 className='text-[10px]'>
              Radius
            </h2>
            <p>
              {planet.radius}
            </p>
              </div>
          <div className='border border-gray-400 px-20 py-4'>
          <h2 className='text-[10px]'>
              Average Temp
            </h2>
            <p>
              {planet.temperature}
            </p>
            </div>
          
          </div>
    </div>
  )
}
