import Head from 'next/head'
import Image from 'next/image'
import data from '../data.json';
import { useState } from 'react';
import pic from '../assets/images/desktop.png';
export default function Home() {
  const [planet, setPlanet] = useState(data[0]);
    console.log(planet);
    
  return (
    <div >
      <Head>
        <title>Planets Fact site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=''>
        <div className='flex text-white justify-between items-center'>
          <img src={planet.images.internal} alt='logo' className='h-10 w-10' />
          
            <div>
            <h1>
              {planet.name}
            </h1>
            <p>
              {planet.overview.content}
            </p>
            <p>
              {planet.overview.source}
            </p>
          <div>
            <h2>
              overview
            </h2>
            <h2>
              internal structure
            </h2>
            <h2>
              surface geology
            </h2>
          </div>
          </div>
      </div>
      </div>
      
    </div>
  )
}
